version: '2'
services:
  hadoop:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcapitanio/hadoop:2.6.0-cdh5.11.1
    networks:
    - hadoop
    external_links:
    - zookeeper
    ports:
    - 50070:50070
    - 50075:50075
    - 8020:8020
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
networks:
  default:
    external:
      name: hadoop
  hadoop:
    driver: bridge
