version: "3"
services:
  hadoop:
    container_name: hadoop
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hadoop:2.8.5
    external_links:
    - zookeeper
    ports:
    - "50070:50070"
    - "50075:50075"
    - "8020:8020"
    - "8042:8042"
    - "8088:8088"
    - "8188:8188"
    - "19888:19888"
networks:
  default:
    external:
      name: parrot_default