version: "2"

services:

    zookeeper:
        image: confluent/zookeeper
        ports:
            - "2181:2181"
        networks:
            - hadoop
        restart: "no"
    
    hadoop:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/hadoop:latest
        links:
            - zookeeper
        networks:
            - hadoop
        volumes:
            - hadoop_conf:/opt/hadoop/etc/hadoop
            - hadoop_logs:/opt/hadoop/logs
            - hadoop_hdfs:/hdfs
        ports:
            - "50070:50070"
            - "8042:804"
            - "8088:8088"
            - "8188:8188"
            - "19888:19888"
        restart: "no"

volumes:
    hadoop_conf:
    hadoop_hdfs:
    hadoop_logs:

networks:
    hadoop:
        driver: bridge
