version: "2"

services:

    zookeeper:
        extends:
            file:   zookeeper.yml
            service: zookeeper

    hadoop:
        image: mcapitanio/hadoop:latest
        links:
            - zookeeper
        networks:
            - hadoop
        volumes:
            - hadoop_conf:/opt/hadoop/etc/hadoop
            - hadoop_logs:/opt/hadoop/logs
            - hadoop_hdfs:/hdfs
        ports:
            - "50070:50070"
            - "50075:50075"
            - "8020:8020"
            - "8042:8042"
            - "8088:8088"
            - "8188:8188"
            - "19888:19888"
        environment:
            http_proxy: http://10.0.2.2:3128
            https_proxy: http://10.0.2.2:3128
            no_proxy: localhost,hadoop,zookeeper

volumes:
    hadoop_conf:
    hadoop_hdfs:
    hadoop_logs:
    zookeeper_data:
    zookeeper_logs:
    zookeeper_conf:

networks:
    hadoop:
        driver: bridge
