version: "3"

services:

    zookeeper:
        image: parrotstream/zookeeper:latest
        ports:
        - 2181:2181
        - 2888:2888
        - 3888:3888
        - 8080:8080
        networks:
        - parrot
    hadoop:
        build:
            context: .
            dockerfile: Dockerfile
        image: parrotstream/hadoop:2.8.5
        links:
            - zookeeper
        networks:
            - parrot
        ports:
            - "50070:50070"
            - "50075:50075"
            - "8020:8020"
            - "8042:8042"
            - "8088:8088"
            - "8188:8188"
            - "19888:19888"
networks:
    default:
      external:
        name: parrot
    parrot:
        driver: bridge
