version: "3"

services:

    zookeeper:
        image: parrotstream/zookeeper
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        networks:
            - parrot

    hadoop:
        build:
            context: .
            dockerfile: Dockerfile
        image: parrotstream/hadoop:2.7.3
        links:
            - zookeeper
        networks:
            - parrot
        volumes:
            - hadoop_conf:/opt/hadoop/etc/hadoop
            - hadoop_logs:/opt/hadoop/logs
            - hadoop_hdfs:/hdfs
        ports:
            - "50070:50070"
            - "50075:50075"
            - "8020:8020"
            - "8042:8042"
            - "8088:8088"
            - "8188:8188"
            - "19888:19888"

volumes:
    hadoop_conf:
    hadoop_hdfs:
    hadoop_logs:

networks:
    parrot:
        driver: bridge
