version: "3"
services:
  hadoop:
    container_name: hadoop
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hadoop:2.7.7
    external_links:
    - zookeeper
    ports:
    - 127.0.0.1:50070:50070
    - 127.0.0.1:50075:50075
    - 127.0.0.1:8020:8020
    - 127.0.0.1:8042:8042
    - 127.0.0.1:8088:8088
    - 127.0.0.1:8188:8188
    - 127.0.0.1:19888:19888
networks:
  default:
    external:
      name: parrot_default
