version: '3'
services:
  zookeeper:
    image: parrotstream/zookeeper:3.4.8
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
    networks:
    - parrot
  hadoop:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/hadoop:latest
    networks:
    - parrot
    external_links:
    - zookeeper
    ports:
    - 9870:9870
    - 9864:9864
    - 8020:8020
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
